

---

---
# Medidas Estatísticas

Este notebook apresenta cálculos de medidas estatísticas (de posição e de dispersão) utilizando diferentes funções (bibliotecas):

* Módulo de estatística do Python ([statistics](https://docs.python.org/3/library/statistics.html#module-statistics))
* Módulo de estatística da biblioteca Numpy ([statistics](https://numpy.org/doc/stable/reference/routines.statistics.html?highlight=statistics))
* Módulo de estatística da biblioteca Scipy ([stats](https://docs.scipy.org/doc/scipy/reference/stats.html?highlight=stats#module-scipy.stats))

Os cálculos são feitos em:

1. Array de dados
2. Dataframes



---

---



---
## 1. Array de dados
---

In [46]:
import statistics # módulo de estatística do Python
import math # módulo de matemática do Python
import numpy as np # biblioteca numpy
from scipy import stats # módulo de estatística da biblioteca scipy

dados = np.array([24, 23, 22, 28, 35, 21, 23, 33, 34, 24, 21, 25, 36, 26, 22,
                  30, 32, 25, 26, 33, 34, 21, 31, 25, 31, 26, 25, 35, 33, 31])
print(dados)

[24 23 22 28 35 21 23 33 34 24 21 25 36 26 22 30 32 25 26 33 34 21 31 25
 31 26 25 35 33 31]

##Média

In [48]:
print(dados.sum() / len(dados))

27.833333333333332

In [49]:
print(dados.mean())

27.833333333333332

In [50]:
print(np.mean(dados))

27.833333333333332

In [51]:
print(statistics.mean(dados.astype(float)))

27.833333333333332

##Mediana

In [52]:
print(np.median(dados))

26.0

In [53]:
print(statistics.median(dados))

26.0

##Moda

In [54]:
print(statistics.mode(dados))

25

##Quartis

In [57]:
print(np.quantile(dados,0.25)) # 1o. quartil

24.0

In [58]:
print(np.quantile(dados,0.50)) # 2o. quartil

26.0

In [59]:
print(np.quantile(dados,0.75)) # 3o. quartil

32.75

##Percentis

In [60]:
print(np.percentile(dados,18)) # percentil 18

23.0

## Variância

In [61]:
print(dados.var())

23.47222222222222

In [62]:
print(np.var(dados))

23.47222222222222

##Desvio-padrão

In [64]:
print(dados.std())

4.844813951249544

In [65]:
print(np.std(dados))

4.844813951249544



---
##2. Dataframes
---

## Conjunto de dados

- Fonte: https://www.kaggle.com/uciml/pima-indians-diabetes-database
- Proprietários originais: National Institute of Diabetes and Digestive and Kidney Diseases
- Doadores da base de dados: Vincent Sigillito (vgs@aplcen.apl.jhu.edu),
Research Center, RMI Group Leader, Applied Physics Laboratory, The Johns Hopkins University (1990)

Detalhes sobre o conjunto de dados:

1. Número de instâncias: 768

2. Número de atributos: 8 (mais classe target)

3. Atributos: (todos com valor numérico)
   1. Número de vezes que engravidou (*Pregnancies*)
   2. Concentração de glicose plasmática a 2 horas em um teste de tolerância à glicose oral (*Glucose*)
   3. Pressão arterial diastólica (mm Hg) (*BloodPressure*)
   4. Espessura da dobra da pele do tríceps (mm) (*SkinThickness*)
   5. Insulina sérica de 2 horas (mu U / ml) (*Insulin*)
   6. Índice de massa corporal (peso em kg / (altura em m) ^ 2) (*BMI*)
   7. Função de pedigree de diabetes (*DiabetesPedigreeFunction*)
   8. Idade (anos) (*Age*)
   
4. Variável target (classe): 0 ou 1 (valor de classe 1 é interpretado como "teste positivo para diabetes")

   Classe Valor Número de instâncias
   - 500 => 0
   - 268 => 1

## Leitura dos dados

Vamos começar importando o arquivo CSV "bruto" usando o Pandas.

In [67]:
import pandas as pd

# Clona o repositório da disciplina no Github
!git clone "https://github.com/malegopc/DSBD"
# lê arquivo de dados, atribue NaN para dados faltantes
diabetes = pd.read_csv('DSBD/Datasets/Indians_Diabetes/diabetes.csv', na_values=['?'])
# imprime as 10 primeiras linhas do dataframe
diabetes # mostra as 5 primeiras linhas e as 5 últimas do dataframe

fatal: destination path 'DSBD' already exists and is not an empty directory.

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

## Estatística descritiva
Função describe() mostra um conjutonto de medidas estatísticas descritivas dos dados.

In [73]:
diabetes.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

## Média

In [75]:
print(diabetes['Age'].mean())

33.240885416666664

##Mediana

In [76]:
print(diabetes['Age'].median())

29.0

##Quartil

In [77]:
print(diabetes['Age'].quantile(0.25))

24.0

##Desvio-padrão

In [78]:
print(diabetes['Age'].std())

11.76023154067868